export type HiscoreDataRow = {
  username: string
  skill_total: number
  attack: number
  attackxp: number
  defense: number
  defensexp: number
  strength: number
  strengthxp: number
  hits: number
  hitsxp: number
  ranged: number
  rangedxp: number
  prayer: number
  prayerxp: number
  magic: number
  magicxp: number
  cooking: number
  cookingxp: number
  woodcut: number
  woodcutxp: number
  fishing: number
  fishingxp: number
  firemaking: number
  firemakingxp: number
  crafting: number
  craftingxp: number
  smithing: number
  smithingxp: number
  mining: number
  miningxp: number
}
